Imported Upstream version 1.34.0

diff --git a/p2v/virt-p2v-make-disk.in b/p2v/virt-p2v-make-disk.in
--- a/p2v/virt-p2v-make-disk.in
+++ b/p2v/virt-p2v-make-disk.in
@@ -22,9 +22,23 @@ unset CDPATH
 program="virt-p2v-make-disk"
 version="@PACKAGE_VERSION@"
 
+# Deal with stupid autotools libexecdir-not-expandable crap.
+prefix="@prefix@"
+exec_prefix="@exec_prefix@"
+libexecdir="@libexecdir@"
+
+if [ -n "$VIRT_P2V_DATA_DIR" ]; then
+    datadir="$VIRT_P2V_DATA_DIR"
+    host_libexecdir="$VIRT_P2V_DATA_DIR"
+else
+    datadir="@datadir@/virt-p2v"
+    host_libexecdir="@libexecdir@"
+fi
+
+# Parse the command line arguments.
 TEMP=`getopt \
-        -o o:V \
-        --long help,inject-ssh-identity:,output:,version \
+        -o o:vV \
+        --long arch:,help,inject-ssh-identity:,install:,no-warn-if-partition,output:,verbose,version \
         -n $program -- "$@"`
 if [ $? != 0 ]; then
     echo "$program: problem parsing the command line arguments"
@@ -34,11 +48,13 @@ eval set -- "$TEMP"
 
 output=
 upload=
+verbose=
+declare -a passthru
 
 usage ()
 {
     echo "Usage:"
-    echo "  $program [--options] -o /dev/sdX os-version"
+    echo "  $program [--options] -o /dev/sdX [os-version]"
     echo
     echo "Read $program(1) man page for more information."
     exit $1
@@ -46,17 +62,36 @@ usage ()
 
 while true; do
     case "$1" in
+        --arch)
+            arch="$2"
+            shift 2;;
         --inject-ssh-identity)
             upload="--upload $2:/var/tmp/id_rsa"
             shift 2;;
         -o|--output)
             output="$2"
             shift 2;;
+        -v|--verbose)
+            set +x
+            verbose=1
+            shift;;
+
+        # virt-builder parameters that are passed through.
+        --install)
+            passthru[${#passthru[*]}]="$1"
+            passthru[${#passthru[*]}]="$2"
+            shift 2;;
+
+        --no-warn-if-partition)
+            passthru[${#passthru[*]}]="$1"
+            shift;;
+
+        # help etc.
+        --help)
+            usage 0;;
         -V|--version)
             echo "$program $version"
             exit 0;;
-        --help)
-            usage 0;;
         --)
             shift
             break;;
@@ -71,12 +106,47 @@ if [ -z "$output" ]; then
     exit 1
 fi
 
-if [ $# -ne 1 ]; then
-    echo "$program: Missing os-version.  See $program(1)."
+if [ $# -gt 1 ]; then
+    echo "$program: Too many parameters.  See $program(1)."
     exit 1
 fi
 
-osversion="$1"
+if [ $# -eq 1 ]; then
+    osversion="$1"
+else
+    # If osversion was not set, then we must guess a good value
+    # based on the host distro.
+    if test -f /etc/redhat-release; then
+        osversion="$(virt-builder -l | sort |
+                       @AWK@ '/^fedora-[1-9]/ {print $1}' | tail -1)"
+    elif test -f /etc/debian_version; then
+        osversion="$(virt-builder -l | sort |
+                       @AWK@ '/^debian-[1-9]/ {print $1}' | tail -1)"
+    fi
+    if [ "x$osversion" = "x" ]; then
+        echo "$program: unable to guess a suitable os-version."
+        echo "You must supply one on the command line and output of 'virt-builder -l'."
+        echo "See $program(1) for further details."
+        exit 1
+    fi
+fi
+
+if [ -n "$arch" ]; then
+    arch_option="--arch $arch"
+    virt_p2v_binary="$host_libexecdir/virt-p2v.$arch"
+else
+    virt_p2v_binary="$host_libexecdir/virt-p2v"
+fi
+
+if [ ! -f "$virt_p2v_binary" ]; then
+    echo "$program: cannot find $virt_p2v_binary"
+    if [ -n "$arch" ]; then
+        echo "You used the '--arch' option, so it's likely that you will need to build"
+        echo "an virt-p2v.$arch binary yourself."
+        echo "See guestfs-building(1) section BUILDING i686 32 BIT VIRT-P2V for help."
+    fi
+    exit 1
+fi
 
 # Create a temporary directory and clean it up when we finish.
 tmpdir="$(mktemp -d)"
@@ -85,19 +155,6 @@ cleanup ()
     rm -rf $tmpdir
 }
 trap cleanup INT QUIT TERM EXIT ERR
-
-# Deal with stupid autotools libexecdir-not-expandable crap.
-prefix="@prefix@"
-exec_prefix="@exec_prefix@"
-libexecdir="@libexecdir@"
-
-if [ -n "$VIRT_P2V_DATA_DIR" ]; then
-    datadir="$VIRT_P2V_DATA_DIR"
-    host_libexecdir="$VIRT_P2V_DATA_DIR"
-else
-    datadir="@datadir@/virt-p2v"
-    host_libexecdir="@libexecdir@"
-fi
 
 # Variations depending on the target distro.  The main difference
 # is in the list of distro packages we add to the base appliance.
@@ -113,10 +170,9 @@ EOF
 latest_version="$(cd /lib/modules; ls -1vr | head -1)"
 dracut -f --kver $latest_version
 EOF
-        # Double quotes because we want $tmpdir to be expanded.
-        # Disable SELinux for consistency with virt-p2v-make-kickstart.
+        # Double quotes because we want $tmpdir to be expanded:
         extra_args="
-          --edit /etc/selinux/config:s/^SELINUX=.*/SELINUX=disabled/g
+          --selinux-relabel
           --upload $tmpdir/p2v.conf:/etc/dracut.conf.d/
           --run $tmpdir/post-install
         "
@@ -152,17 +208,24 @@ while read line; do
     fi
 done < $depsfile
 
+# Add -v -x if we're in verbose mode.
+if [ "x$verbose" = "x1" ]; then
+    verbose_option="-v -x"
+fi
+
 # Run virt-builder.  Note we controversially assume systemd here.  We
 # could provide a sysvinit fallback if required.
 virt-builder "$osversion"                                       \
+    $verbose_option						\
     --output "$output"                                          \
+    $arch_option						\
     --update                                                    \
     --install "$install"                                        \
     --root-password password:p2v                                \
     --upload "$datadir"/issue:/etc/issue                        \
     --upload "$datadir"/issue:/etc/issue.net                    \
     --mkdir "$libexecdir"                                       \
-    --upload "$host_libexecdir"/virt-p2v:"$libexecdir"          \
+    --upload "$virt_p2v_binary":"$libexecdir"/virt-p2v          \
     --chmod 0755:"$libexecdir"/virt-p2v                         \
     --upload "$datadir"/launch-virt-p2v:/usr/bin/               \
     --chmod 0755:/usr/bin/launch-virt-p2v                       \
@@ -177,7 +240,8 @@ virt-builder "$osversion"                                       \
         s/^[Login]/[Login]\nReserveVT=1\n/
     '                                                           \
     $upload                                                     \
-    $extra_args
+    $extra_args                                                 \
+    "${passthru[@]}"
 
 # We have to do this so the cleanup() handler runs.
 exit $?
