Imported Upstream version 1.24.0

diff --git a/appliance/init b/appliance/init
--- a/appliance/init
+++ b/appliance/init
@@ -113,6 +113,8 @@ if grep -sq guestfs_verbose=1 /proc/cmdline; then
 fi
 
 if ! grep -sq guestfs_rescue=1 /proc/cmdline; then
+  # Run the daemon.
+
   # Run the daemon under valgrind if ./configure --enable-valgrind-daemon
   if grep -sq guestfs_valgrind_daemon=1 /proc/cmdline; then
     if [ -r /etc/guestfsd.suppressions ]; then
@@ -124,8 +126,16 @@ if ! grep -sq guestfs_rescue=1 /proc/cmdline; then
 
   # Run guestfsd, under valgrind if asked.
   $vg guestfsd
-  if [ $? -eq 119 ]; then echo "DAEMON VALGRIND FAILED"; fi
+  if [ $? -eq 119 ]; then
+      echo "DAEMON VALGRIND FAILED"
+      # Sleep so valgrind messages are seen by the host.  Note this
+      # only happens in non-production builds
+      # (--enable-valgrind-daemon) + on an error path.
+      sleep 10
+  fi
 else
+  # Run virt-rescue shell.
+
   # Remove LD_PRELOAD=libSegFault set above.
   unset LD_PRELOAD
   # Use appliance in rescue mode, also used by the virt-rescue command.
